name: Conventional Commits

on:
  pull_request:
    branches: [development, test, main]
    types: [opened, edited, synchronize, reopened]

jobs:
  validate:
    uses: diegutierrez/.github/.github/workflows/conventional-commits.yml@main
