name: Promote Quality Gate

on:
  pull_request:
    branches: [test, main]

jobs:
  quality-gate:
    uses: diegutierrez/.github/.github/workflows/node-ci.yml@main
    with:
      working-directory: frontend
      node-version: "20"
